[package]
name = "rapini"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rabe = "0.2.6"
rocket = "0.5.0-rc.1"
serde = "1.0.118"
serde_json = "1.0.60"